### ISSUE TITLE
Create Categories

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#11]

**Comment by nwelto** [comment]
# Create a New Category
This is for the implementation of a route that allows the creation of a new category entity.

## Request
- Method: POST
- Path: /categories
- Body

```c#
{
  "label": "Jalapeno Poppers"
}

```

## Response
- Body

```c#
{
  "id": 1,
  "label": "Jalapeno Poppers"
}

```

## Acceptance Criteria
- Status code 201 Created
- No errors
- A response body that matches the intended entity.
