### ISSUE TITLE
Read Categories

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#12]

**Comment by nwelto** [comment]
# Read a Single Category
This ticket is for the implementation of a route that allows the retrieval of details for a single category entity based on its ID.

## Request
- Method: GET
- Path: /categories/{id}

## Response
- Body
```c#
{
  "id": 3,
  "label": "Jalapeno Poppers"
}
```

## Acceptance Criteria
- Status code 200 OK
- No errors
- A response body that matches the requested category entity.
