### ISSUE TITLE
Update Categories

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#13]

**Comment by nwelto** [comment]
# Update a Category
This ticket is for the implementation of a route that allows updating the details of an existing category entity based on its ID.

## Request
- Method: PUT
- Path: /categories/{id}
- Body
```c#
{
  "label": "Jalapeno Poppers"
}
```

## Response
- Body
```c#
{
  "id": 1,
  "label": "Buffalo Sliders"
}

```
## Acceptance Criteria
- Status code 200 OK
- No errors
- The response body reflects the updated category entity.
