### ISSUE TITLE
Delete Categories

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#14]

**Comment by nwelto** [comment]
# Delete a Category
This ticket is for the implementation of a route that allows the deletion of a category entity based on its ID. This operation should remove the category from the system entirely.

## Request
- Method: DELETE
- Path: /categories/{id}

## Response
- Status Code: 204 No Content

## Acceptance Criteria
- Status code 204 No Content
- No errors
- The category with the specified ID is no longer available in the system.
