### ISSUE TITLE
Create Tags

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#15]

**Comment by ctucker0113** [comment]
## Description
This ticket details the implementation of an API route for creating a new tag. The endpoint should allow clients to add a new tag with a unique label.

## Request
Method: POST

Path: /api/tags

## Response
Body:
```c#
{
  "label": "new tag label"
}
```

## Response
Body (example response):
```c#
{
  "id": {newTagID},
  "label": "new tag label"
}
```

## Acceptance Criteria

- The route should correctly create a new tag with the provided label.

- Upon successful creation, the server should respond with a status code of 201 Created.
