### ISSUE TITLE
Get All Tags

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#16]

**Comment by ctucker0113** [comment]
## Description

This ticket requests the implementation of a route that retrieves all tags.

## Request

Method: GET
Path : /api/tags

## Response:

- Body:

```c#
[
   {
    "id": {tagID1},
    "label": "tag label 1"
   },
   {
    "id": {tagID2},
    "label": "tag label 2"
   }
]
```

## Acceptance Criteria
- Status Code: 200 OK
