### ISSUE TITLE
Update Tags

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#17]

**Comment by ctucker0113** [comment]
## Description
This ticket outlines the development of an API route for updating an existing tag's details. This route should allow for modifications to the tag's label while keeping its unique ID the same.

## Request
Method: PUT
Path: /api/tags/{tagID}

Body:
```c#
{
  "label": "new tag label"
}
```

Response
Body (example response):

```c#
{
  "id": {tagID},
  "label": "updated tag label"
}
```

## Acceptance Criteria

- The route should correctly update the label of the tag associated with the provided tagID.

- The server should respond with **a status code of 200 OK upon successful update**, including the updated tag details in the response body.

- **If the tagID does not exist in the database, the server should respond with a 404 Not Found** status code and an appropriate error message.
