### ISSUE TITLE
Delete Tags

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#18]

**Comment by ctucker0113** [comment]
## Description
This ticket involves the creation of an API route to delete a specific tag identified by its unique ID.

## Request
Method: DELETE

Path: /api/tags/{tagID}

## Response
The response should not contain a body for a successful deletion.

## Acceptance Criteria

- The route should correctly delete the tag associated with the provided tagID.

- **Upon successful deletion, the server should respond with a status code of 204 No Content**, indicating that the operation was successful and there is no content to return.

- **If the tagID does not exist in the database, the server should respond with a 404 Not Found status code** and an appropriate error message.

- Proper validation of the tagID in the request is required. **If the tagID format is incorrect, the server should return a 400 Bad Request status code** and a descriptive error message.
