### ISSUE TITLE
Create a Post Tag (Add Tag to Post)

### ISSUE THREAD

**Issue by ctucker0113** [Bonni535/e24-rare-meta-server#23]

**Comment by Bonni535** [comment]
# Add Tag to a Post
This is for the implementation of a route that allows to add a tag on a post.
## Request
- Method: Post
- Path: /posts/{postId}/tags
- Body
```c#
{
  "id": int,
  "author_id": int, 
  "post_id": "string",
  "content": "varchar",
  "created_on": "dateTime",
}
```
## Response
- Body
```c#
{
  "id": int,
  "author_id": int, 
  "post_id": "string",
  "content": "varchar",
  "created_on": "dateTime",
}
```
## Acceptance Criteria
- Status code 201 Created
- No errors
- A response body that matches the intended entity.

## Dev Notes
This will be a Post request, here's an example from a previous project:
```c#
app.MapPost("/posts/{postId}/tags", (int postId, List<int> tagIds) =>
{
  "postId": 1,
  "tagIds": ["tag1", "tag2", ]
}
```
