### ISSUE TITLE
Create Comment

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#6]

**Comment by Bonni535** [comment]
# Create a new Comment
This is for the implementation of a route that allows the creation of a new comment entity.
## Request
- Method: POST
- Path: /comments
- Body
```c#
{
  "id": int,
  "author_id": int, 
  "post_id": "string",
  "content": "varchar",
  "created_on": "dateTime",
}
```
## Response
- Body
```c#
{
  "id": int,
  "author_id": int, 
  "post_id": "string",
  "content": "varchar",
  "created_on": "dateTime",
}
```
## Acceptance Criteria
- Status code 201 Created
- No errors
- A response body that matches the intended entity.

## Dev Notes
This will be a Post request, here's an example from a previous project:
```c#
app.MapPost("/api/servicetickets", (ServiceTicket serviceTicket) =>
{
    serviceTicket.Id = serviceTickets.Max(st => st.Id) + 1;
    serviceTickets.Add(serviceTicket);
    return serviceTicket;
});
```
