### ISSUE TITLE
Read All the Post's Comments

### ISSUE THREAD

**Issue by GregM1992** [Bonni535/e24-rare-meta-server#7]

**Comment by Bonni535** [comment]
# Read all the Post's Comments
This is for the implementation of a route that allows to view all the comments on a post.
## Request
- Method: Get
- Path: /posts/{id}/comments
- Body
```c#
{
  "id": int,
  "author_id": int, 
  "post_id": "string",
  "content": "varchar",
  "created_on": "dateTime",
}
```
## Response
- Body
```c#
{
  "id": int,
  "author_id": int, 
  "post_id": "string",
  "content": "varchar",
  "created_on": "dateTime",
}
```
## Acceptance Criteria
- Status code 201 Created
- No errors
- A response body that matches the intended entity.

## Dev Notes
This will be a Get request, here's an example from a previous project:
```c#
app.MapGet("/api/customers/{id}", (int id) =>
{
    Customer customer = customers.FirstOrDefault(c => c.Id == id);
    if (customer == null)
    {
        return Results.NotFound();
    }
    customer.ServiceTicket = serviceTickets.FirstOrDefault(st => st.CustomerId == id);
    return Results.Ok(customer);
});
```
